# Generated by Django 2.1.2 on 2018-10-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181025_1826'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teaching_assistants',
        ),
        migrations.AddField(
            model_name='teachersteachcourses',
            name='students',
            field=models.ManyToManyField(related_name='Students', to='accounts.Student'),
        ),
        migrations.AddField(
            model_name='teachersteachcourses',
            name='teaching_assistants',
            field=models.ManyToManyField(related_name='TAs', to='accounts.Student'),
        ),
    ]
