# Generated by Django 2.1.2 on 2018-12-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20181028_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersteachcourses',
            name='teaching_assistants',
            field=models.ManyToManyField(blank=True, null=True, related_name='TAs', to='accounts.Student'),
        ),
    ]
