# Generated by Django 2.0.5 on 2019-01-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20181223_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersteachcourses',
            name='teaching_assistants',
            field=models.ManyToManyField(blank=True, related_name='TAs', to='accounts.Student'),
        ),
    ]
