# Generated by Django 2.1.2 on 2019-01-04 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181223_1231'),
        ('courses', '0004_auto_20190103_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='teachersteachcourses',
            name='students',
        ),
        migrations.AddField(
            model_name='teachersteachcourses',
            name='students',
            field=models.ManyToManyField(related_name='Students', through='courses.StudentAttendCourses', to='accounts.Student'),
        ),
        migrations.AddField(
            model_name='studentattendcourses',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.TeachersTeachCourses'),
        ),
        migrations.AddField(
            model_name='studentattendcourses',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student'),
        ),
    ]
