# Generated by Django 2.1.2 on 2019-01-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20190104_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersteachcourses',
            name='student_code',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='teachersteachcourses',
            name='ta_code',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teachersteachcourses',
            name='teaching_assistants',
            field=models.ManyToManyField(blank=True, related_name='TAs', to='accounts.Teacher'),
        ),
    ]
