# Generated by Django 2.1.2 on 2018-11-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='begin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='end',
            field=models.DateTimeField(null=True),
        ),
    ]
