# Generated by Django 2.1.2 on 2018-11-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_auto_20181104_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='begin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
