# Generated by Django 2.1.2 on 2018-11-04 13:24

from django.db import migrations, models
import lectures.models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0003_auto_20181104_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectureimage',
            name='image',
            field=models.ImageField(upload_to=lectures.models.get_file_path),
        ),
    ]
