# Generated by Django 2.1.2 on 2018-11-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0004_auto_20181104_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='begin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='end',
            field=models.DateTimeField(),
        ),
    ]
